package UI;

import BL.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class JFDeleteEmployees extends javax.swing.JFrame {

    Principal p;

    public JFDeleteEmployees() {
        initComponents();
        p = new Principal();
    }

    public JFDeleteEmployees(Principal p) {
        initComponents();

        this.p = p;
        jcb_ShowData.setModel(new DefaultComboBoxModel(p.showEmployee().toArray()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_Name = new javax.swing.JTextField();
        jlb_Name = new javax.swing.JLabel();
        jlb_LastName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtf_LastName = new javax.swing.JTextField();
        jtf_Phone = new javax.swing.JTextField();
        jlb_Id = new javax.swing.JLabel();
        jtf_Id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_Delete = new javax.swing.JButton();
        jcb_ShowData = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jbl_EmployeeId = new javax.swing.JLabel();
        jbl_Token = new javax.swing.JLabel();
        jtf_EmployeeId = new javax.swing.JTextField();
        jtf_Token = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_Email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtf_Name.setEditable(false);

        jlb_Name.setText("Name");

        jlb_LastName.setText("LastName");

        jLabel4.setText("Phone");

        jtf_LastName.setEditable(false);

        jtf_Phone.setEditable(false);

        jlb_Id.setText("Id");

        jtf_Id.setEditable(false);

        jLabel1.setText("Information");

        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        jcb_ShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_ShowDataActionPerformed(evt);
            }
        });

        jLabel3.setText("Select item to delete:");

        jbl_EmployeeId.setText("Employee Id");

        jbl_Token.setText("Token");

        jtf_EmployeeId.setEditable(false);

        jtf_Token.setEditable(false);

        jLabel2.setText("Email");

        jtf_Email.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jcb_ShowData, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbl_EmployeeId)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(55, 55, 55)
                            .addComponent(jtf_Email))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jbl_Token)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_Token, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlb_LastName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlb_Name)
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel1))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jlb_Id))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtf_Phone)
                                .addComponent(jtf_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_EmployeeId)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jcb_ShowData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_Name)
                    .addComponent(jtf_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_LastName)
                    .addComponent(jtf_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_Id))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_EmployeeId)
                    .addComponent(jtf_EmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Token, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbl_Token))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btn_Delete)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed

        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected client?", "Delete", JOptionPane.YES_NO_OPTION);

        if (option == 0) {
            try {

                p.deletePerson(Integer.parseInt(jtf_Id.getText()));
                JOptionPane.showMessageDialog(null, "Employee deleted successfully");

                jtf_Name.setText("");
                jtf_LastName.setText("");
                jtf_Phone.setText("");
                jtf_Id.setText("");
                jtf_Token.setText("");
                jtf_EmployeeId.setText("");
                jtf_Email.setText("");

                jcb_ShowData.setModel(new DefaultComboBoxModel(p.showEmployee().toArray()));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR");
            }
        }

    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void jcb_ShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_ShowDataActionPerformed
        Employee e = (((Employee) jcb_ShowData.getSelectedItem()));
        jtf_Name.setText(e.name);
        jtf_LastName.setText(e.lastName);
        jtf_Phone.setText(Integer.toString(e.phone));
        jtf_Id.setText(Integer.toString(e.getId()));
        jtf_Token.setText(Integer.toString(e.getToken()));
        jtf_EmployeeId.setText(Integer.toString(e.getEmployeeId()));
        jtf_Email.setText(e.email);

    }//GEN-LAST:event_jcb_ShowDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFDeleteEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFDeleteEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFDeleteEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDeleteEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDeleteEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jbl_EmployeeId;
    private javax.swing.JLabel jbl_Token;
    private javax.swing.JComboBox<Employee> jcb_ShowData;
    private javax.swing.JLabel jlb_Id;
    private javax.swing.JLabel jlb_LastName;
    private javax.swing.JLabel jlb_Name;
    private javax.swing.JTextField jtf_Email;
    private javax.swing.JTextField jtf_EmployeeId;
    private javax.swing.JTextField jtf_Id;
    private javax.swing.JTextField jtf_LastName;
    private javax.swing.JTextField jtf_Name;
    private javax.swing.JTextField jtf_Phone;
    private javax.swing.JTextField jtf_Token;
    // End of variables declaration//GEN-END:variables
}
