package UI;

import BL.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class JFDeleteAccounts extends javax.swing.JFrame {

    Principal p;

    public JFDeleteAccounts() {
        initComponents();
        p = new Principal();
    }

    public JFDeleteAccounts(Principal p) {
        initComponents();

        this.p = p;
        jcb_ShowDataSavingAccount.setModel(new DefaultComboBoxModel(p.showSavingsAccount().toArray()));
        jcb_ShowDataBorrowing.setModel(new DefaultComboBoxModel(p.showBorrowing().toArray()));
        jcb_ShowDataTargetAccount.setModel(new DefaultComboBoxModel(p.showTargetAccount().toArray()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_DeleteSavingAccount = new javax.swing.JButton();
        jcb_ShowDataSavingAccount = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jlb_Number3 = new javax.swing.JLabel();
        jtf_SavingsAccountNumber = new javax.swing.JTextField();
        jtf_SavingsAccountBalance = new javax.swing.JTextField();
        jlb_Balance3 = new javax.swing.JLabel();
        jlb_interest3 = new javax.swing.JLabel();
        jtf_SavingsAccountInterest = new javax.swing.JTextField();
        jtf_SavingsAccountDepositAmount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_DeleteBorrowing = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcb_ShowDataBorrowing = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jlb_Number4 = new javax.swing.JLabel();
        jtf_BorrowingNumber = new javax.swing.JTextField();
        jtf_BorrowingBalance = new javax.swing.JTextField();
        jlb_Balance4 = new javax.swing.JLabel();
        jlb_interest4 = new javax.swing.JLabel();
        jtf_BorrowingInterest = new javax.swing.JTextField();
        jtf_BorrowingStartingAmount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtf_BorrowingExpirationDate = new javax.swing.JTextField();
        jtf_BorrowingQuotasAmount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtf_BorrowingMonthlyPayment = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_DeleteTargetAccount = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcb_ShowDataTargetAccount = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jlb_Number2 = new javax.swing.JLabel();
        jtf_TargetAccountNumber = new javax.swing.JTextField();
        jtf_TargetAccountBalance = new javax.swing.JTextField();
        jlb_Balance2 = new javax.swing.JLabel();
        jlb_interest2 = new javax.swing.JLabel();
        jtf_TargetAccountInterest = new javax.swing.JTextField();
        jtf_TargetAccountMonthlyAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtf_TargetAccountQuotasAmount = new javax.swing.JTextField();
        jtf_TargetAccountQuotasMade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Information");

        btn_DeleteSavingAccount.setText("Delete");
        btn_DeleteSavingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteSavingAccountActionPerformed(evt);
            }
        });

        jcb_ShowDataSavingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_ShowDataSavingAccountActionPerformed(evt);
            }
        });

        jLabel3.setText("Select item to delete:");

        jlb_Number3.setText("Number");

        jtf_SavingsAccountNumber.setEditable(false);

        jtf_SavingsAccountBalance.setEditable(false);

        jlb_Balance3.setText("Balance");

        jlb_interest3.setText("Interest");

        jtf_SavingsAccountInterest.setEditable(false);

        jtf_SavingsAccountDepositAmount.setEditable(false);

        jLabel10.setText("Deposit Amount");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jcb_ShowDataSavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_DeleteSavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(205, 205, 205))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(207, 207, 207)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlb_Number3)
                            .addComponent(jlb_Balance3)
                            .addComponent(jlb_interest3))
                        .addComponent(jLabel10))
                    .addGap(38, 38, 38)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_SavingsAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_SavingsAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_SavingsAccountInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jtf_SavingsAccountDepositAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(208, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcb_ShowDataSavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(btn_DeleteSavingAccount)
                .addGap(108, 108, 108))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_Number3)
                        .addComponent(jtf_SavingsAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_Balance3)
                        .addComponent(jtf_SavingsAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_interest3)
                        .addComponent(jtf_SavingsAccountInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jtf_SavingsAccountDepositAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(156, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Saving Account", jPanel4);

        btn_DeleteBorrowing.setText("Delete");
        btn_DeleteBorrowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteBorrowingActionPerformed(evt);
            }
        });

        jLabel2.setText("Information");

        jcb_ShowDataBorrowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_ShowDataBorrowingActionPerformed(evt);
            }
        });

        jLabel4.setText("Select item to delete:");

        jlb_Number4.setText("Number");

        jtf_BorrowingNumber.setEditable(false);

        jlb_Balance4.setText("Balance");

        jlb_interest4.setText("Interest");

        jLabel11.setText("Starting Amount");

        jLabel12.setText("Expirtation Date");

        jLabel13.setText("Quotas Amount");

        jLabel14.setText("Monthly Payment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_ShowDataBorrowing, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel2)))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_DeleteBorrowing, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlb_Number4)
                            .addComponent(jlb_Balance4)
                            .addComponent(jlb_interest4))
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14))
                    .addGap(33, 33, 33)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtf_BorrowingBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtf_BorrowingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtf_BorrowingInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtf_BorrowingStartingAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jtf_BorrowingExpirationDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtf_BorrowingQuotasAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jtf_BorrowingMonthlyPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(207, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcb_ShowDataBorrowing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(btn_DeleteBorrowing)
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_Number4)
                        .addComponent(jtf_BorrowingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_Balance4)
                        .addComponent(jtf_BorrowingBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_interest4)
                        .addComponent(jtf_BorrowingInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jtf_BorrowingStartingAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jtf_BorrowingExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jtf_BorrowingQuotasAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jtf_BorrowingMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(93, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Borrowing", jPanel1);

        btn_DeleteTargetAccount.setText("Delete");
        btn_DeleteTargetAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteTargetAccountActionPerformed(evt);
            }
        });

        jLabel5.setText("Information");

        jcb_ShowDataTargetAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_ShowDataTargetAccountActionPerformed(evt);
            }
        });

        jLabel6.setText("Select item to delete:");

        jlb_Number2.setText("Number");

        jtf_TargetAccountNumber.setEditable(false);

        jtf_TargetAccountBalance.setEditable(false);

        jlb_Balance2.setText("Balance");

        jlb_interest2.setText("Interest");

        jtf_TargetAccountInterest.setEditable(false);

        jtf_TargetAccountMonthlyAmount.setEditable(false);

        jLabel7.setText("Monthly Amount");

        jLabel8.setText("Quotas Amount");

        jtf_TargetAccountQuotasAmount.setEditable(false);

        jtf_TargetAccountQuotasMade.setEditable(false);

        jLabel9.setText("Quotas Made");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_DeleteTargetAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_ShowDataTargetAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel5)))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(207, 207, 207)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlb_Number2)
                            .addComponent(jlb_Balance2)
                            .addComponent(jlb_interest2))
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addGap(38, 38, 38)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_TargetAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_TargetAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_TargetAccountInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jtf_TargetAccountMonthlyAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtf_TargetAccountQuotasAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jtf_TargetAccountQuotasMade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(207, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcb_ShowDataTargetAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(btn_DeleteTargetAccount)
                .addGap(65, 65, 65))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_Number2)
                        .addComponent(jtf_TargetAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_Balance2)
                        .addComponent(jtf_TargetAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlb_interest2)
                        .addComponent(jtf_TargetAccountInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jtf_TargetAccountMonthlyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jtf_TargetAccountQuotasAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jtf_TargetAccountQuotasMade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(114, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Target Account", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_ShowDataSavingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_ShowDataSavingAccountActionPerformed
        SavingsAccount c = (((SavingsAccount) jcb_ShowDataSavingAccount.getSelectedItem()));
        jtf_SavingsAccountNumber.setText(Long.toString(c.number));
        jtf_SavingsAccountInterest.setText(Float.toString(c.getInterest()));
        jtf_SavingsAccountBalance.setText(Float.toString(c.getBalance()));
        jtf_SavingsAccountDepositAmount.setText(Float.toString(c.getDepositAmount()));
    }//GEN-LAST:event_jcb_ShowDataSavingAccountActionPerformed

    private void btn_DeleteSavingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteSavingAccountActionPerformed

        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected account?", "Delete", JOptionPane.YES_NO_OPTION);

        if (option == 0) {
            try {

                p.deleteAccount(Long.parseLong(jtf_SavingsAccountNumber.getText()));
                JOptionPane.showMessageDialog(null, "Savings Account deleted successfully");

                jtf_SavingsAccountNumber.setText("");
                jtf_SavingsAccountDepositAmount.setText("");
                jtf_SavingsAccountInterest.setText("");
                jtf_SavingsAccountBalance.setText("");
                jcb_ShowDataSavingAccount.setModel(new DefaultComboBoxModel(p.showSavingsAccount().toArray()));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error deleting the account");
            }
        }
    }//GEN-LAST:event_btn_DeleteSavingAccountActionPerformed

    private void btn_DeleteBorrowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteBorrowingActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected account?", "Delete", JOptionPane.YES_NO_OPTION);

        if (option == 0) {
            try {

                p.deleteAccount(Long.parseLong(jtf_BorrowingNumber.getText()));
                JOptionPane.showMessageDialog(null, "Account deleted successfully");

                jtf_BorrowingNumber.setText("");
                jtf_BorrowingInterest.setText("");
                jtf_BorrowingBalance.setText("");
                jtf_BorrowingExpirationDate.setText("");
                jtf_BorrowingStartingAmount.setText("");
                jtf_BorrowingMonthlyPayment.setText("");
                jtf_BorrowingQuotasAmount.setText("");
                jcb_ShowDataBorrowing.setModel(new DefaultComboBoxModel(p.showBorrowing().toArray()));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR");
            }
        }
    }//GEN-LAST:event_btn_DeleteBorrowingActionPerformed

    private void jcb_ShowDataBorrowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_ShowDataBorrowingActionPerformed

        Borrowing b = (((Borrowing) jcb_ShowDataBorrowing.getSelectedItem()));
        jtf_BorrowingNumber.setText(Long.toString(b.number));
        jtf_BorrowingInterest.setText(Float.toString(b.getInterest()));
        jtf_BorrowingBalance.setText(Float.toString(b.getBalance()));
        //jtf_BorrowingExpirationDate.setText(sdf(b.getExpirationDate()));
        jtf_BorrowingStartingAmount.setText(Float.toString(b.getStartingAmount()));
        jtf_BorrowingMonthlyPayment.setText(Float.toString(b.getMonthlyPayment()));
        jtf_BorrowingQuotasAmount.setText(Integer.toString(b.getQuotasAmount()));

    }//GEN-LAST:event_jcb_ShowDataBorrowingActionPerformed

    private void btn_DeleteTargetAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteTargetAccountActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected account?", "Delete", JOptionPane.YES_NO_OPTION);

        if (option == 0) {
            try {

                p.deleteAccount(Long.parseLong(jtf_TargetAccountNumber.getText()));
                JOptionPane.showMessageDialog(null, "Target Account deleted successfully");

                jtf_TargetAccountNumber.setText("");
                jtf_TargetAccountBalance.setText("");
                jtf_TargetAccountInterest.setText("");
                jtf_TargetAccountMonthlyAmount.setText("");
                jtf_TargetAccountQuotasAmount.setText("");
                jtf_TargetAccountQuotasMade.setText("");
                jcb_ShowDataTargetAccount.setModel(new DefaultComboBoxModel(p.showTargetAccount().toArray()));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error deleting the account");
            }
        }
    }//GEN-LAST:event_btn_DeleteTargetAccountActionPerformed

    private void jcb_ShowDataTargetAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_ShowDataTargetAccountActionPerformed
        TargetAccount ta = (((TargetAccount) jcb_ShowDataTargetAccount.getSelectedItem()));
        jtf_TargetAccountNumber.setText(Long.toString(ta.number));
        jtf_TargetAccountInterest.setText(Float.toString(ta.getInterest()));
        jtf_TargetAccountBalance.setText(Float.toString(ta.getBalance()));
        jtf_TargetAccountMonthlyAmount.setText(Float.toString(ta.getMonthlyAmount()));
        jtf_TargetAccountQuotasAmount.setText(Integer.toString(ta.getQuotasAmount()));
        jtf_TargetAccountQuotasMade.setText(Integer.toString(ta.getQuotasMade()));

    }//GEN-LAST:event_jcb_ShowDataTargetAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFDeleteAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFDeleteAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFDeleteAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDeleteAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDeleteAccounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DeleteBorrowing;
    private javax.swing.JButton btn_DeleteSavingAccount;
    private javax.swing.JButton btn_DeleteTargetAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<Borrowing> jcb_ShowDataBorrowing;
    private javax.swing.JComboBox<SavingsAccount> jcb_ShowDataSavingAccount;
    private javax.swing.JComboBox<TargetAccount> jcb_ShowDataTargetAccount;
    private javax.swing.JLabel jlb_Balance2;
    private javax.swing.JLabel jlb_Balance3;
    private javax.swing.JLabel jlb_Balance4;
    private javax.swing.JLabel jlb_Number2;
    private javax.swing.JLabel jlb_Number3;
    private javax.swing.JLabel jlb_Number4;
    private javax.swing.JLabel jlb_interest2;
    private javax.swing.JLabel jlb_interest3;
    private javax.swing.JLabel jlb_interest4;
    private javax.swing.JTextField jtf_BorrowingBalance;
    private javax.swing.JTextField jtf_BorrowingExpirationDate;
    private javax.swing.JTextField jtf_BorrowingInterest;
    private javax.swing.JTextField jtf_BorrowingMonthlyPayment;
    private javax.swing.JTextField jtf_BorrowingNumber;
    private javax.swing.JTextField jtf_BorrowingQuotasAmount;
    private javax.swing.JTextField jtf_BorrowingStartingAmount;
    private javax.swing.JTextField jtf_SavingsAccountBalance;
    private javax.swing.JTextField jtf_SavingsAccountDepositAmount;
    private javax.swing.JTextField jtf_SavingsAccountInterest;
    private javax.swing.JTextField jtf_SavingsAccountNumber;
    private javax.swing.JTextField jtf_TargetAccountBalance;
    private javax.swing.JTextField jtf_TargetAccountInterest;
    private javax.swing.JTextField jtf_TargetAccountMonthlyAmount;
    private javax.swing.JTextField jtf_TargetAccountNumber;
    private javax.swing.JTextField jtf_TargetAccountQuotasAmount;
    private javax.swing.JTextField jtf_TargetAccountQuotasMade;
    // End of variables declaration//GEN-END:variables
}
