package UI;

import BL.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class JFUpdateAccounts extends javax.swing.JFrame {

    Principal p;
    SavingsAccount sa;
    Borrowing b;
    TargetAccount ta;

    public JFUpdateAccounts() {
        initComponents();
        p = new Principal();
    }

    public JFUpdateAccounts(Principal p) {
        initComponents();

        this.p = p;
        jcb_ShowDataSavingAccount.setModel(new DefaultComboBoxModel(p.showSavingsAccount().toArray()));
        jcb_ShowDataBorrowing.setModel(new DefaultComboBoxModel(p.showBorrowing().toArray()));
        jcb_ShowDataTargetAccount.setModel(new DefaultComboBoxModel(p.showTargetAccount().toArray()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jtf_NumberSavingAccount = new javax.swing.JTextField();
        jlb_Number = new javax.swing.JLabel();
        jlb_Interest = new javax.swing.JLabel();
        jlb_Balance = new javax.swing.JLabel();
        jtf_InterestSavingAccount = new javax.swing.JTextField();
        jtf_BalanceSavingAccount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_UpdateSavingAccount = new javax.swing.JButton();
        jcb_ShowDataSavingAccount = new javax.swing.JComboBox<SavingsAccount>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_UpdateBorrowing = new javax.swing.JButton();
        jtf_BorrowingBalance = new javax.swing.JTextField();
        jlb_Balance1 = new javax.swing.JLabel();
        jlb_Interest1 = new javax.swing.JLabel();
        jtf_BorrowingInterest = new javax.swing.JTextField();
        jtf_BorrowingNumber = new javax.swing.JTextField();
        jlb_Number1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcb_ShowDataBorrowing = new javax.swing.JComboBox<Borrowing>();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_UpdateTargetAccount = new javax.swing.JButton();
        jtf_BalanceTargetAccount = new javax.swing.JTextField();
        jlb_Balance2 = new javax.swing.JLabel();
        jlb_Interest2 = new javax.swing.JLabel();
        jtf_InterestTargetAccount = new javax.swing.JTextField();
        jtf_NumberTargetAccount = new javax.swing.JTextField();
        jlb_Number2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcb_ShowDataTargetAccount = new javax.swing.JComboBox<TargetAccount>();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtf_NumberSavingAccount.setEditable(false);

        jlb_Number.setText("Number");

        jlb_Interest.setText("Interest");

        jlb_Balance.setText("Balance");

        jLabel1.setText("Information");

        btn_UpdateSavingAccount.setText("Upadate");
        btn_UpdateSavingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateSavingAccountActionPerformed(evt);
            }
        });

        jcb_ShowDataSavingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_ShowDataSavingAccountActionPerformed(evt);
            }
        });

        jLabel3.setText("Select item to delete:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jcb_ShowDataSavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_Interest)
                            .addComponent(jlb_Number)
                            .addComponent(jlb_Balance))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btn_UpdateSavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtf_NumberSavingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jtf_InterestSavingAccount)
                            .addComponent(jtf_BalanceSavingAccount))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jcb_ShowDataSavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_Number)
                            .addComponent(jtf_NumberSavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_Interest)
                            .addComponent(jtf_InterestSavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtf_BalanceSavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlb_Balance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btn_UpdateSavingAccount)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Saving Account", jPanel4);

        btn_UpdateBorrowing.setText("Update");
        btn_UpdateBorrowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateBorrowingActionPerformed(evt);
            }
        });

        jlb_Balance1.setText("Balance");

        jlb_Interest1.setText("Interest");

        jtf_BorrowingNumber.setEditable(false);

        jlb_Number1.setText("Number");

        jLabel2.setText("Information");

        jcb_ShowDataBorrowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_ShowDataBorrowingActionPerformed(evt);
            }
        });

        jLabel4.setText("Select item to delete:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jcb_ShowDataBorrowing, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_Interest1)
                            .addComponent(jlb_Number1)
                            .addComponent(jlb_Balance1))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btn_UpdateBorrowing, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtf_BorrowingNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jtf_BorrowingInterest)
                            .addComponent(jtf_BorrowingBalance))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jcb_ShowDataBorrowing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_Number1)
                            .addComponent(jtf_BorrowingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_Interest1)
                            .addComponent(jtf_BorrowingInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtf_BorrowingBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlb_Balance1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btn_UpdateBorrowing)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Borrowing", jPanel1);

        btn_UpdateTargetAccount.setText("Update");
        btn_UpdateTargetAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateTargetAccountActionPerformed(evt);
            }
        });

        jlb_Balance2.setText("Balance");

        jlb_Interest2.setText("Interest");

        jtf_NumberTargetAccount.setEditable(false);

        jlb_Number2.setText("Number");

        jLabel5.setText("Information");

        jcb_ShowDataTargetAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_ShowDataTargetAccountActionPerformed(evt);
            }
        });

        jLabel6.setText("Select item to delete:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jcb_ShowDataTargetAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_Interest2)
                            .addComponent(jlb_Number2)
                            .addComponent(jlb_Balance2))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btn_UpdateTargetAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtf_NumberTargetAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jtf_InterestTargetAccount)
                            .addComponent(jtf_BalanceTargetAccount))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jcb_ShowDataTargetAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_Number2)
                            .addComponent(jtf_NumberTargetAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_Interest2)
                            .addComponent(jtf_InterestTargetAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtf_BalanceTargetAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlb_Balance2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btn_UpdateTargetAccount)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Target Account", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_ShowDataSavingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_ShowDataSavingAccountActionPerformed
        sa = (((SavingsAccount) jcb_ShowDataSavingAccount.getSelectedItem()));
        jtf_NumberSavingAccount.setText(Long.toString(sa.number));
        jtf_InterestSavingAccount.setText(Float.toString(sa.getInterest()));
        jtf_BalanceSavingAccount.setText(Float.toString(sa.getBalance()));
    }//GEN-LAST:event_jcb_ShowDataSavingAccountActionPerformed

    private void btn_UpdateSavingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateSavingAccountActionPerformed

        sa.setNumber(Long.parseLong(jtf_NumberSavingAccount.getText()));
        sa.setBalance(Float.parseFloat(jtf_BalanceSavingAccount.getText()));
        sa.setInterest(Float.parseFloat(jtf_InterestSavingAccount.getText()));

        p.updateAccount(sa);

        JOptionPane.showMessageDialog(null, "Account updated successfully");

        jtf_NumberSavingAccount.setText("");
        jtf_BalanceSavingAccount.setText("");
        jtf_InterestSavingAccount.setText("");

        jcb_ShowDataSavingAccount.setModel(new DefaultComboBoxModel(p.showSavingsAccount().toArray()));
    }//GEN-LAST:event_btn_UpdateSavingAccountActionPerformed

    private void btn_UpdateBorrowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateBorrowingActionPerformed
        b.setNumber(Long.parseLong(jtf_BorrowingNumber.getText()));
        b.setBalance(Float.parseFloat(jtf_BorrowingBalance.getText()));
        b.setInterest(Float.parseFloat(jtf_BorrowingInterest.getText()));

        p.updateAccount(b);

        JOptionPane.showMessageDialog(null, "Account updated successfully");

        jtf_BorrowingNumber.setText("");
        jtf_BorrowingInterest.setText("");
        jtf_BorrowingBalance.setText("");

        jcb_ShowDataBorrowing.setModel(new DefaultComboBoxModel(p.showBorrowing().toArray()));
    }//GEN-LAST:event_btn_UpdateBorrowingActionPerformed

    private void jcb_ShowDataBorrowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_ShowDataBorrowingActionPerformed
        b = (((Borrowing) jcb_ShowDataBorrowing.getSelectedItem()));
        jtf_BorrowingNumber.setText(Long.toString(b.number));
        jtf_BorrowingInterest.setText(Float.toString(b.getInterest()));
        jtf_BorrowingBalance.setText(Float.toString(b.getBalance()));
    }//GEN-LAST:event_jcb_ShowDataBorrowingActionPerformed

    private void btn_UpdateTargetAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateTargetAccountActionPerformed
        ta.setNumber(Long.parseLong(jtf_NumberTargetAccount.getText()));
        ta.setBalance(Float.parseFloat(jtf_BalanceTargetAccount.getText()));
        ta.setInterest(Float.parseFloat(jtf_InterestTargetAccount.getText()));

        p.updateAccount(ta);

        JOptionPane.showMessageDialog(null, "Account updated successfully");

        jtf_NumberTargetAccount.setText("");
        jtf_InterestTargetAccount.setText("");
        jtf_BalanceTargetAccount.setText("");

        jcb_ShowDataTargetAccount.setModel(new DefaultComboBoxModel(p.showTargetAccount().toArray()));
    }//GEN-LAST:event_btn_UpdateTargetAccountActionPerformed

    private void jcb_ShowDataTargetAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_ShowDataTargetAccountActionPerformed
        ta = (((TargetAccount) jcb_ShowDataTargetAccount.getSelectedItem()));
        jtf_NumberTargetAccount.setText(Long.toString(ta.number));
        jtf_InterestTargetAccount.setText(Float.toString(ta.getInterest()));
        jtf_BalanceTargetAccount.setText(Float.toString(ta.getBalance()));
    }//GEN-LAST:event_jcb_ShowDataTargetAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFUpdateAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFUpdateAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFUpdateAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUpdateAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFUpdateAccounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_UpdateBorrowing;
    private javax.swing.JButton btn_UpdateSavingAccount;
    private javax.swing.JButton btn_UpdateTargetAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<Borrowing> jcb_ShowDataBorrowing;
    private javax.swing.JComboBox<SavingsAccount> jcb_ShowDataSavingAccount;
    private javax.swing.JComboBox<TargetAccount> jcb_ShowDataTargetAccount;
    private javax.swing.JLabel jlb_Balance;
    private javax.swing.JLabel jlb_Balance1;
    private javax.swing.JLabel jlb_Balance2;
    private javax.swing.JLabel jlb_Interest;
    private javax.swing.JLabel jlb_Interest1;
    private javax.swing.JLabel jlb_Interest2;
    private javax.swing.JLabel jlb_Number;
    private javax.swing.JLabel jlb_Number1;
    private javax.swing.JLabel jlb_Number2;
    private javax.swing.JTextField jtf_BalanceSavingAccount;
    private javax.swing.JTextField jtf_BalanceTargetAccount;
    private javax.swing.JTextField jtf_BorrowingBalance;
    private javax.swing.JTextField jtf_BorrowingInterest;
    private javax.swing.JTextField jtf_BorrowingNumber;
    private javax.swing.JTextField jtf_InterestSavingAccount;
    private javax.swing.JTextField jtf_InterestTargetAccount;
    private javax.swing.JTextField jtf_NumberSavingAccount;
    private javax.swing.JTextField jtf_NumberTargetAccount;
    // End of variables declaration//GEN-END:variables
}
